
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.result.DeleteResult;
import com.mongodb.client.result.UpdateResult;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import org.bson.types.ObjectId;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Aplicacion extends javax.swing.JFrame {
    //"mongodb+srv://Admin:sergioguz9@cluster0.7drou.mongodb.net/ejemplo1?retryWrites=true&w=majority"
    MongoDatabase baseDatos;
    MongoCollection<Document> coleccion;
    DefaultTableModel m = new DefaultTableModel();
    String idGlobal="";
    /**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
        //"mongodb+srv://EduardoAdmin:<password>@cluster0.hltkq.mongodb.net/<dbname>?retryWrites=true&w=majority")
        try{
            baseDatos = (MongoDatabase) new ConexionAtlas(
                new MongoClientURI("mongodb+srv://EduardoAdmin:edimir123@cluster0.hltkq.mongodb.net/PRODUCTOSDB?retryWrites=true&w=majority")
            ).getDatabase("PRODUCTOSDB");
            coleccion = baseDatos.getCollection("PRODUCTOS");
            m.addColumn("ID");
            m.addColumn("DESCRIPCION");
            m.addColumn("PRECIO");
            m.addColumn("EXISTENCIA");
            jTable1.setModel(m);
            btnActualizar.setEnabled(false);
            cargarDatos();
        }catch(Exception ex){ mensaje(ex.getMessage());}
    }
    private void mensaje(String m){JOptionPane.showMessageDialog(null,m);}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDes = new javax.swing.JTextField();
        txtP = new javax.swing.JTextField();
        txtEx = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ins.png"))); // NOI18N
        btnInsertar.setText("INSERTAR");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        jLabel1.setText("DESCRIPCION :                                              PRECIO :                                               EXISTENCIAS :    ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIPCION", "PRECIO", "EXISTENCIA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aa.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leer.png"))); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/act.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(29, 29, 29)
                .addComponent(btnCargar)
                .addGap(37, 37, 37)
                .addComponent(btnActualizar)
                .addGap(449, 449, 449))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDes, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(txtEx, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(btnInsertar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnInsertar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnCargar)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try{
            Document insertar = new Document();
            insertar.put("Dexcripcion", txtDes.getText());
            insertar.put("Precio", txtP.getText());
            insertar.put("Edad",Integer.parseInt(txtEx.getText()));
            coleccion.insertOne(insertar);
            limpiarCampos();
            mensaje("Se inserto correctamente el registro");
            cargarDatos();
        }catch(Exception e){mensaje(e.getMessage());}
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(!estaSeleccionado()){
            mensaje("ERROR\nDebes seleccionar una fila de la tabla para poder borrar");
        }
        int fila = jTable1.getSelectedRow();
        idGlobal = m.getValueAt(fila, 0).toString();
        int resp = JOptionPane.showConfirmDialog(this,"¿Estas segura que deseas borrar ID"+idGlobal+"?");
        if(resp== JOptionPane.OK_OPTION){
            if(eliminar(idGlobal)==true){
                mensaje("Se elimino correctamente");
                cargarDatos();
            }else{
                mensaje("No se pudo eliminar el ID"+idGlobal);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        if(!estaSeleccionado()){
            mensaje("ERROR\nDebes seleccionar una fila de la tabla para poder borrar");
            return;
        }
        int fila = jTable1.getSelectedRow();
        idGlobal = m.getValueAt(fila, 0).toString();
        txtDes.setText(m.getValueAt(fila, 1).toString());
        txtP.setText(m.getValueAt(fila, 2).toString());
        txtEx.setText(m.getValueAt(fila, 3).toString());
        btnInsertar.setEnabled(false);
        btnActualizar.setEnabled(true);
        
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try{
            if(idGlobal.isEmpty()){
                mensaje("ID VACIO");
                return;
            }
            Document filtro  = new Document("_id", new ObjectId(idGlobal));
            Document dataActualizar = new Document();
            dataActualizar.put("Descripcion", txtDes.getText());
            dataActualizar.put("Precio", txtP.getText());
            dataActualizar.put("Existencia", Integer.parseInt(txtEx.getText()));
            
            UpdateResult resultado = coleccion.updateOne(filtro, new Document("$set",dataActualizar));
            if(resultado.getMatchedCount()==1){
                mensaje("SE ACTUALIZO LOS DATOS");
                cargarDatos();
                limpiarCampos();
            }else{
                mensaje("ERROR\nNo se pudo actualizar");
            }
        }catch(Exception e){mensaje(e.getMessage());}
        btnInsertar.setEnabled(true);
        btnActualizar.setEnabled(false);
    }//GEN-LAST:event_btnActualizarActionPerformed
    private boolean eliminar(String id){
        try{
            Document eliminar = new Document("_id",new ObjectId(id));
            DeleteResult resultado = coleccion.deleteOne(eliminar);
            if(resultado.getDeletedCount()==1){
                return true;
            }else{
                return false;
            }
        }catch(Exception e){ mensaje(e.getMessage());}
        return false;
    }
    private boolean estaSeleccionado(){
        if(jTable1.getSelectedRow()>=0){
            return true;
        }
        return false;
    }
    public void limpiarCampos(){
        txtDes.setText("");
        txtP.setText("");
        txtEx.setText("");
        
    }
    public void cargarDatos(){
        try{
            MongoCursor<Document> documentos = coleccion.find().iterator();
            if(m.getRowCount()!=0){
                int total = m.getRowCount();
                for (int i = 1; i <= total; i++) {
                    m.removeRow(0);
                }
            }
            while(documentos.hasNext()){
                String[] renglon = new String[5];
                ArrayList<Object> doc = new ArrayList(documentos.next().values());
                renglon[0] = doc.get(0).toString();
                renglon[1] = doc.get(1).toString();
                renglon[2] = doc.get(2).toString();
                renglon[3] = doc.get(3).toString();
                
                m.addRow(renglon);
            }
        }catch(Exception e){mensaje(e.getMessage());}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtEx;
    private javax.swing.JTextField txtP;
    // End of variables declaration//GEN-END:variables
}
